language: node_js
node_js:
  - 'lts/*'

cache:
  directories:
    - 'node_modules'

install:
  - npm install -g codecov
  - npm install

script:
  - npm test -- --coverage

after_success:
  - codecov
  - npm run build

deploy:
  provider: firebase
  api_key: $FIREBASE_AUTH_TOKEN
  skip_cleanup: true
