language: node_js
node_js:
  - 'lts/*'

cache:
  directories:
    - 'node_modules'

install:
  - npm install

script:
  - npm test

deploy:
  provider: heroku
  token: $HEROKU_AUTH_TOKEN
  app: react-picture-copy
